; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "DAMQT320"
#define MyAppVersion "3.2.0"
#define MyAppExeName "DAMQT320.exe"
#define MyShortAppName "DAMQT320"
#define MyLongAppName "DAMQT320"
#define INI_DataDirKey "DataDirectory"

; IMPORTANT !!! Check that the following variables are pointing to the right addresses (See sources below for details)
#define DAM320_DIR "D:\rafa\DAMQT_3.2.0_Release\src\DAM320"  
#define DAMZERNIKE_DIR "D:\rafa\DAMQT_3.2.0_Release\src\DAMZernike320"
#define DAMGUI320_DIR "D:\rafa\DAMQT_3.2.0_Release\src\DAMGUI320"
#define IMAGES_DIR "D:\rafa\DAMQT_3.2.0\src\DAMGUI320\images"
#define INTERFACES_DIR "D:\rafa\DAMQT_3.2.0_Release\src\interfaces_320" 
;#define INTERFACES_PYTHON_DIR "D:\rafa\DAMQT_3.2.0\src\interfaces_320"
#define LIB_FORTRAN_DIR "C:\Qt\Tools\mingw730_64\bin"
#define LICENSE_DIR "D:\rafa\DAMQT_3.2.0\license"
#define MANUAL_DIR "D:\rafa\DAMQT_3.2.0\doc\manual"
#define MINGW_DLL_DIR "C:\msys64\mingw64\bin"
#define MINGW_LIB_DIR "C:\msys64\mingw64\lib"
#define OPENBABEL_DIR "C:\Program Files\OpenBabel-3.1.1"
;#define MSYS64_DLL_DIR "C:\msys64\usr\bin"
;#define PYTHON_DIR "C:\msys64\usr\bin"
;#define PYTHON_LIB_DIR "C:\msys64\mingw64\bin\"
#define OUTPUT_DIR "D:\rafa\DAMQT_3.2.0\windows"
#define SAMPLES_DIR "D:\rafa\DAMQT_3.2.0\samples"
#define TDAM320_DIR "D:\rafa\DAMQT_3.2.0_Release\src\TDAM320"
#define QT_BIN_DIR "C:\msys64\mingw64\bin"
#define QT_LIB_DIR "C:\msys64\mingw64\lib"
#define QT_PLATFORMS_DIR "C:\msys64\mingw64\share\qt5\plugins\platforms"
;#define QT_BIN_DIR "C:\Qt\5.12.3\mingw73_64\bin"
;#define QT_LIB_DIR "C:\Qt\5.12.3\mingw73_64\lib"
;#define QT_PLATFORMS_DIR "C:\Qt\5.12.3\mingw73_64\plugins\platforms"
#define OPENGL32_DIR "C:\WINDOWS\SYSTEM32"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId= {{610542D0-3E03-4689-8B27-8DECD7185A46}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile="{#LICENSE_DIR}\COPYING"
OutputDir="{#OUTPUT_DIR}"
OutputBaseFilename=DAMQT320_64b_setup
SetupIconFile={#IMAGES_DIR}\damqt.ico
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon="{app}\damqt.ico"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "corsican"; MessagesFile: "compiler:Languages\Corsican.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "greek"; MessagesFile: "compiler:Languages\Greek.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "norwegian"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "serbiancyrillic"; MessagesFile: "compiler:Languages\SerbianCyrillic.isl"
Name: "serbianlatin"; MessagesFile: "compiler:Languages\SerbianLatin.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: {code:GetDataDir}; Check: not DataDirExists; Flags:uninsneveruninstall; Permissions: users-modify

[Files]
; DAM320 exec files
Source: "{#DAM320_DIR}\compareplt320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMDEN320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMDENGRAD320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMFIELD320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMFIELDPNT320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMFORCES320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMFRAD320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMGTO320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMISODEN320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMISOPOT320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMMULTROT320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMORB320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMPOT320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMSGHOLE320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\DAMSTO320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\dmat_GAUSSIAN_to_DAM.exe"; DestDir: "{app}"; Flags: ignoreversion

Source: "{#DAM320_DIR}\readcnt.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\readdamqt320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\readplt320.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\sgbs2sxyz.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAM320_DIR}\subtractplt320.exe"; DestDir: "{app}"; Flags: ignoreversion

; DAMZernike exec files
Source: "{#DAMZERNIKE_DIR}\DAMZernike-Jacobi_GTO.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAMZERNIKE_DIR}\DAMZernike-Jacobi_STO.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DAMZERNIKE_DIR}\DAMDENZJ320.exe"; DestDir: "{app}"; Flags: ignoreversion

; GUI320 exec files
Source: "{#DAMGUI320_DIR}\DAMQT320.exe"; DestDir: "{app}"; Flags: ignoreversion

; interfaces exec files
Source: "{#INTERFACES_DIR}\GAUSS_interface.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#INTERFACES_DIR}\MOLEKEL_interface.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#INTERFACES_DIR}\MOLPRO_out_interface.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#INTERFACES_DIR}\NWChem_interface.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#INTERFACES_DIR}\TURBOMOLE_interface.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#INTERFACES_DIR}\Mopac_aux_interface.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#INTERFACES_PYTHON_DIR}\MOLPRO_xml_interface.py"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#INTERFACES_PYTHON_DIR}\MOPAC_aux_interface.py"; DestDir: "{app}"; Flags: ignoreversion

; TDAM320 exec files
Source: "{#TDAM320_DIR}\DAMTOPOGRAPHY.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#TDAM320_DIR}\DAMMESPIMIZER.exe"; DestDir: "{app}"; Flags: ignoreversion

; Manual
Source: "{#MANUAL_DIR}\DAMQT_3.2.0_manual.pdf"; DestDir: "{app}"; Flags: ignoreversion

; Python
;Source: "{#PYTHON_DIR}\python2.7.exe"; DestDir: "{app}"; Flags: ignoreversion

; Dynamic libraries for MINGW
Source: "{#MINGW_DLL_DIR}\libbz2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libfreetype-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#LIB_FORTRAN_DIR}\libgfortran-4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libglib-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libgraphite2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libharfbuzz-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libiconv-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libicudt68.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libicuin68.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libicuuc68.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libintl-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libpcre-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libpcre16-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libpng16-16.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libquadmath-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#MINGW_DLL_DIR}\opengl32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENGL32_DIR}\OPENGL32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MINGW_DLL_DIR}\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#PYTHON_LIB_DIR}\libpython2.7.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#MSYS64_DLL_DIR}\msys-2.0.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#MSYS64_DLL_DIR}\msys-python2.7.dll"; DestDir: "{app}"; Flags: ignoreversion


; Static libraries for MINGW
;Source: "{#MINGW_LIB_DIR}\libpng16.dll.a"; DestDir: "{app}"; Flags: ignoreversion

; Dynamic libraries for Qt5
;Source: "{#QT_BIN_DIR}\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#QT_BIN_DIR}\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion

Source: "{#QT_BIN_DIR}\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#QT_BIN_DIR}\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#QT_BIN_DIR}\Qt5OpenGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#QT_BIN_DIR}\Qt5PrintSupport.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#QT_BIN_DIR}\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion

; Static libraries for Qt5
Source: "{#QT_LIB_DIR}\libQt5PlatformCompositorSupport.a"; DestDir: "{app}"; Flags: ignoreversion

; Plugin for windows platform
Source: "{#QT_PLATFORMS_DIR}\qwindows.dll"; DestDir: "{app}\platforms"; Flags: ignoreversion 


; OpenBabel
Source: "{#OPENBABEL_DIR}\bz2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\cairo.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\expat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\fontconfig.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\formats_cairo.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\formats_common.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\formats_compchem.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\formats_json.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\formats_misc.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\formats_utility.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\formats_xml.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\freetype.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\jsoncpp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\libcharset.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\libiconv.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\libinchi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\libpng16.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\libxml2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obabel.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obconformer.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obdepict.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obdistgen.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\OBDotNet.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obenergy.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obfit.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obfitall.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obgen.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obgrep.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obminimize.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obmm.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obprobe.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obprop.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obrms.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obrotamer.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obrotate.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obspectrophore.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obsym.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obtautomer.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\obthermo.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\openbabel.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\openbabel_csharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\openbabel_java.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\openbabel-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\plugin_charges.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\plugin_descriptors.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\plugin_fingerprints.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\plugin_forcefields.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\plugin_ops.obf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\sdf.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\vc_redist.x64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\xdr.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OPENBABEL_DIR}\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion


; Samples 
Source: "{#SAMPLES_DIR}\*"; Check: InstallSampleData; DestDir: "{code:GetDataDir}";  Flags: confirmoverwrite recursesubdirs uninsneveruninstall

; Images
Source: "{#IMAGES_DIR}\damqt.ico"; DestDir: "{app}";

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\damqt.ico"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"; IconFilename: "{app}\damqt.ico"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\damqt.ico"


[INI]
Filename: "{app}\{#MyShortAppName}.ini"; Section: "{#MyShortAppName}"; Key: "DataDirectory"; String: "{code:GetDataDir}"; Flags: createkeyifdoesntexist

[Code]
// global vars
var
  DataDirPage: TInputDirWizardPage;
  SampleDataPage: TInputOptionWizardPage;
  DataDirVal: String;
 
function GetDataDir(Param: String): String;
begin
  { Return the selected DataDir }
  Result := DataDirPage.Values[0];
end;
 
function GetDefaultDataDirectory() : String;
begin
  Result := ExpandConstant('{localappdata}\{#MyShortAppName}');
end;
 
function GetIniFilename() : String;
begin
    Result :=  WizardDirValue() + '\{#MyShortAppName}.ini';
end;
 
  // custom wizard page setup, for data dir.
procedure InitializeWizard;
var
  myLocalAppData: String;
begin
  DataDirPage := CreateInputDirPage(
    wpSelectDir,
    '{#MyLongAppName} Samples Directory',
    '',
    'Please select a directory to install {#MyShortAppName} samples to.',
    False,
    '{#MyShortAppName}'
  );
  DataDirPage.Add('');
 
  DataDirPage.Values[0] := GetIniString('{#MyShortAppName}', '{#INI_DataDirKey}', GetDefaultDataDirectory(), GetIniFilename());
  
  SampleDataPage := CreateInputOptionPage(DataDirPage.ID,
    'Install Sample Data', 'The sample data enable to check the application.',
    'Should the sample data be installed?( Recommended for new users )',
    True, False);
  SampleDataPage.Add('Install');
  SampleDataPage.Add('Do not install');

  SampleDataPage.Values[0] := True;
  
end;
 
function DataDirExists(): Boolean;
begin
  { Find out if data dir already exists }
  Result := DirExists(GetDataDir(''));
end;

function InstallSampleData(): Boolean;
begin
  { Return the value of the 'install' radiobutton }
  //MsgBox('InstallSampleData.', mbError, MB_OK);
  Result := SampleDataPage.Values[0];
end;

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
